// Headless reproduction harness for the remaining per-cell meshing artifacts
// seen in screenshot 2026-06-13 104038 (flat caps, floating faceted blobs,
// hard bands). It faithfully replicates the cluster's three-radius pipeline
// WITHOUT a GL context (no UploadMesh / BLAS), since those layers are not under
// test:
//
//   * cell CREATION  -> mark_cells_dirty_around_particle: box floor((p +/- 2r)/s)
//                       (cluster.cpp:132-160, influence_radius = 2*r)
//   * particle ASSIGN-> intersects_sphere, closest-point-on-AABB <= r
//                       (cluster.cpp:246-251 + cell.cpp:83-95)
//   * field EVAL     -> CalculateScalarAndMaterial search radius 2.5*r
//                       (surface.c:713)
//   * cell box / mesh-> center=(C+0.5)*s, size=s, divisionPow=4
//                       (cell.cpp:59-75, 271-278)
//
// Meshes are produced by the real GenerateMesh + simplify_mesh, so any seam,
// crack, clipped cap, or floating component is generated by the genuine
// algorithm. Oracles run on the combined CPU triangle soup:
//
//   1. boundary-edge count  : welded edges used by exactly 1 triangle. A closed
//                             blob -> 0. Cracks / flat caps at a cell face show
//                             up as a ring of boundary edges.
//   2. connected components : floating blobs that don't blend -> >1 component.
//   3. coverage gap         : analytic union-of-spheres surface points whose
//                             nearest mesh triangle is farther than tolerance
//                             -> a clipped / missing region.

#include <cstdio>
#include <cmath>
#include <cstdint>
#include <vector>
#include <map>
#include <unordered_map>
#include <algorithm>

#include "raylib.h"
#include "mesh_simplifier.hpp"

// SurfaceLib is compiled as C; declare the bits we call with C linkage (mirrors
// the manual forward declarations in cell.cpp, which also avoids including
// surface.h -> raymath.h C++ operator overloads inside extern "C").
extern "C" {
    typedef struct {
        Vector3 center;
        Vector3 size;
        int     divisionPow;
    } Bounds;

    typedef struct {
        Vector3 position;
        float   radius;
        int     materialId;
    } Particle;

    Mesh GenerateMesh(Particle* particles, float particleRadius, int particleCount, Bounds volume, float blendWidth, Particle* clipParticles, int clipCount);
    void ComputeSurfaceNormals(Mesh* mesh, Particle* particles, float particleRadius, int particleCount, float blendWidth, Particle* clipParticles, int clipCount);
}

// ----------------------------------------------------------------------------
// Test scene description
// ----------------------------------------------------------------------------
struct PIn {
    Vector3 pos;
    float    r;
    uint32_t mat;
};

struct CoordKey {
    int x, y, z;
    bool operator==(const CoordKey& o) const { return x==o.x && y==o.y && z==o.z; }
};
struct CoordHash {
    size_t operator()(const CoordKey& k) const {
        return (size_t)(k.x*73856093) ^ (size_t)(k.y*19349663) ^ (size_t)(k.z*83492791);
    }
};

static int ifloor(float v) { return (int)floorf(v); }

// Mirror of Cell::intersects_sphere against the box of integer coord (cx,cy,cz).
static bool box_intersects_sphere(int cx, int cy, int cz, float s, Vector3 c, float r) {
    float minx = cx*s, miny = cy*s, minz = cz*s;
    float maxx = (cx+1)*s, maxy = (cy+1)*s, maxz = (cz+1)*s;
    float qx = fmaxf(minx, fminf(c.x, maxx));
    float qy = fmaxf(miny, fminf(c.y, maxy));
    float qz = fmaxf(minz, fminf(c.z, maxz));
    float dx = c.x-qx, dy = c.y-qy, dz = c.z-qz;
    return (dx*dx+dy*dy+dz*dz) <= r*r;
}

// ----------------------------------------------------------------------------
// Combined triangle soup + oracles
// ----------------------------------------------------------------------------
struct Soup {
    std::vector<Vector3> verts;   // 3 per triangle (non-indexed, world space)
    std::vector<Vector3> norms;   // matching per-vertex normal (0 if mesh had none)
};

static void append_mesh(Soup& soup, const Mesh& m) {
    if (m.vertexCount == 0 || m.triangleCount == 0 || !m.vertices) return;
    auto pushN = [&](int idx){
        if (m.normals) soup.norms.push_back(Vector3{ m.normals[idx*3+0], m.normals[idx*3+1], m.normals[idx*3+2] });
        else soup.norms.push_back(Vector3{0,0,0});
    };
    if (m.indices) {
        for (int i = 0; i < m.triangleCount*3; ++i) {
            unsigned short idx = m.indices[i];
            soup.verts.push_back(Vector3{ m.vertices[idx*3+0], m.vertices[idx*3+1], m.vertices[idx*3+2] });
            pushN(idx);
        }
    } else {
        for (int i = 0; i < m.triangleCount*3; ++i) {
            pushN(i);
            soup.verts.push_back(Vector3{ m.vertices[i*3+0], m.vertices[i*3+1], m.vertices[i*3+2] });
        }
    }
}

// Weld vertices on a quantization grid so independent per-cell meshes that meet
// on a shared face plane fuse into one topology.
static std::vector<int> weld(const Soup& soup, float eps) {
    // Key on the exact quantized integer coordinates (not a hashed scalar) so
    // that distinct world positions can NEVER alias together. A previous
    // XOR-hash key produced collisions that merged far-apart sphere points,
    // fabricating phantom non-manifold edges and normal "seams" that don't
    // exist in the actual mesh.
    struct QKey { long long x,y,z; bool operator==(const QKey&o)const{return x==o.x&&y==o.y&&z==o.z;} };
    struct QHash { size_t operator()(const QKey&k)const{
        return (size_t)(k.x*73856093LL) ^ (size_t)(k.y*19349663LL) ^ (size_t)(k.z*83492791LL);
    } };
    std::unordered_map<QKey, int, QHash> grid;
    grid.reserve(soup.verts.size()*2);
    std::vector<int> canon(soup.verts.size());
    auto key = [eps](const Vector3& v) -> QKey {
        return QKey{ (long long)llroundf(v.x/eps),
                     (long long)llroundf(v.y/eps),
                     (long long)llroundf(v.z/eps) };
    };
    int next = 0;
    for (size_t i = 0; i < soup.verts.size(); ++i) {
        QKey k = key(soup.verts[i]);
        auto it = grid.find(k);
        if (it == grid.end()) { grid[k] = next; canon[i] = next; ++next; }
        else canon[i] = it->second;
    }
    return canon;
}

struct OracleResult {
    long long triangles = 0;
    long long boundary_edges = 0;   // edges used by exactly 1 triangle
    long long nonmanifold_edges = 0;// edges used by >2 triangles (total)
    long long nonman_on_plane = 0;  // ...of which lie on a cell-boundary plane
    long long nonman_interior = 0;  // ...of which lie in a cell interior
    int components = 0;
    int coverage_misses = 0;        // analytic surface samples with no nearby tri
    float max_gap = 0.0f;
    int normal_seam_verts = 0;      // welded verts whose per-cell normals disagree
    float max_normal_angle = 0.0f;  // degrees
};

// Union-find for connected components over welded vertices.
struct DSU {
    std::vector<int> p;
    void init(int n){ p.resize(n); for(int i=0;i<n;++i) p[i]=i; }
    int find(int a){ while(p[a]!=a){ p[a]=p[p[a]]; a=p[a]; } return a; }
    void uni(int a,int b){ p[find(a)]=find(b); }
};

// Meshed (isosurface) radius: surface.c contours at field = -adaptiveOffset,
// where adaptiveOffset = max(0,(cellSize/r - 1)*r*0.3) and cellSize = s/15 for
// divisionPow=4. So the union boundary lives at r - offset.
static inline float meshed_radius(float r, float s) {
    float gridStep = s / 15.0f;
    float ratio = gridStep / r;
    float offset = ratio > 1.0f ? (ratio-1.0f)*r*0.3f : 0.0f;
    return r - offset;
}

// Squared distance from point p to triangle (a,b,c). Ericson, Real-Time
// Collision Detection (closest-point-on-triangle via Voronoi regions).
static inline float point_tri_dist2(const Vector3& p, const Vector3& a,
                                    const Vector3& b, const Vector3& c) {
    Vector3 ab{b.x-a.x, b.y-a.y, b.z-a.z};
    Vector3 ac{c.x-a.x, c.y-a.y, c.z-a.z};
    Vector3 ap{p.x-a.x, p.y-a.y, p.z-a.z};
    float d1 = ab.x*ap.x+ab.y*ap.y+ab.z*ap.z;
    float d2 = ac.x*ap.x+ac.y*ap.y+ac.z*ap.z;
    if (d1 <= 0.0f && d2 <= 0.0f) { Vector3 q{p.x-a.x,p.y-a.y,p.z-a.z}; return q.x*q.x+q.y*q.y+q.z*q.z; }
    Vector3 bp{p.x-b.x, p.y-b.y, p.z-b.z};
    float d3 = ab.x*bp.x+ab.y*bp.y+ab.z*bp.z;
    float d4 = ac.x*bp.x+ac.y*bp.y+ac.z*bp.z;
    if (d3 >= 0.0f && d4 <= d3) { Vector3 q{p.x-b.x,p.y-b.y,p.z-b.z}; return q.x*q.x+q.y*q.y+q.z*q.z; }
    float vc = d1*d4 - d3*d2;
    if (vc <= 0.0f && d1 >= 0.0f && d3 <= 0.0f) {
        float v = d1 / (d1 - d3);
        Vector3 q{a.x+v*ab.x-p.x, a.y+v*ab.y-p.y, a.z+v*ab.z-p.z};
        return q.x*q.x+q.y*q.y+q.z*q.z;
    }
    Vector3 cp{p.x-c.x, p.y-c.y, p.z-c.z};
    float d5 = ab.x*cp.x+ab.y*cp.y+ab.z*cp.z;
    float d6 = ac.x*cp.x+ac.y*cp.y+ac.z*cp.z;
    if (d6 >= 0.0f && d5 <= d6) { Vector3 q{p.x-c.x,p.y-c.y,p.z-c.z}; return q.x*q.x+q.y*q.y+q.z*q.z; }
    float vb = d5*d2 - d1*d6;
    if (vb <= 0.0f && d2 >= 0.0f && d6 <= 0.0f) {
        float w = d2 / (d2 - d6);
        Vector3 q{a.x+w*ac.x-p.x, a.y+w*ac.y-p.y, a.z+w*ac.z-p.z};
        return q.x*q.x+q.y*q.y+q.z*q.z;
    }
    float va = d3*d6 - d5*d4;
    if (va <= 0.0f && (d4-d3) >= 0.0f && (d5-d6) >= 0.0f) {
        float w = (d4-d3) / ((d4-d3) + (d5-d6));
        Vector3 q{b.x+w*(c.x-b.x)-p.x, b.y+w*(c.y-b.y)-p.y, b.z+w*(c.z-b.z)-p.z};
        return q.x*q.x+q.y*q.y+q.z*q.z;
    }
    float denom = 1.0f / (va + vb + vc);
    float v = vb * denom, w = vc * denom;
    Vector3 q{a.x+ab.x*v+ac.x*w-p.x, a.y+ab.y*v+ac.y*w-p.y, a.z+ab.z*v+ac.z*w-p.z};
    return q.x*q.x+q.y*q.y+q.z*q.z;
}

static OracleResult run_oracles(const Soup& soup, const std::vector<PIn>& particles, float s, float ratio) {
    OracleResult res;
    res.triangles = (long long)soup.verts.size()/3;
    if (res.triangles == 0) return res;

    float eps = s * 1e-3f;
    if (const char* e = getenv("CONT_EPS")) eps = (float)atof(e);
    std::vector<int> canon = weld(soup, eps);
    int vcount = 0;
    for (int c : canon) vcount = std::max(vcount, c+1);

    // Edge use counts.
    std::map<std::pair<int,int>, int> edge_uses;
    DSU dsu; dsu.init(vcount);
    for (long long t = 0; t < res.triangles; ++t) {
        int a = canon[t*3+0], b = canon[t*3+1], c = canon[t*3+2];
        int e[3][2] = {{a,b},{b,c},{c,a}};
        for (auto& pr : e) {
            int u = pr[0], v = pr[1];
            if (u==v) continue; // degenerate after weld
            if (u>v) std::swap(u,v);
            edge_uses[{u,v}]++;
            dsu.uni(u,v);
        }
    }
    // Map canonical id -> a representative position (first soup vertex seen).
    std::vector<Vector3> cpos(vcount, Vector3{NAN,NAN,NAN});
    for (size_t i=0;i<canon.size();++i)
        if (std::isnan(cpos[canon[i]].x)) cpos[canon[i]] = soup.verts[i];

    bool verbose = getenv("CONT_VERBOSE") != nullptr;
    auto on_cell_plane = [&](float v){
        float m = v / s; return fabsf(m - roundf(m)) < 1e-3f;
    };
    double edge_len_sum = 0.0; long long edge_len_cnt = 0;
    for (auto& kv : edge_uses) {
        const Vector3& ea = cpos[kv.first.first];
        const Vector3& eb = cpos[kv.first.second];
        edge_len_sum += sqrtf((ea.x-eb.x)*(ea.x-eb.x)+(ea.y-eb.y)*(ea.y-eb.y)+(ea.z-eb.z)*(ea.z-eb.z));
        edge_len_cnt++;
        if (kv.second == 1) res.boundary_edges++;
        else if (kv.second > 2) {
            res.nonmanifold_edges++;
            // Classify by location. A non-manifold edge ON a cell-boundary plane
            // means two cells tore apart / fused wrong at their shared face -- a
            // real, visible defect. An edge in a cell INTERIOR is the marching
            // cubes hard-union artifact: where a sharp concave crease (two-sphere
            // intersection) falls inside a cell, the MC table emits a folded
            // internal sheet (4-/6-valence edges at grid vertices). That sheet is
            // buried inside the opaque solid, so it is tracked but not failed.
            const Vector3& a = cpos[kv.first.first];
            const Vector3& b = cpos[kv.first.second];
            Vector3 mid{ (a.x+b.x)*0.5f, (a.y+b.y)*0.5f, (a.z+b.z)*0.5f };
            if (on_cell_plane(mid.x) || on_cell_plane(mid.y) || on_cell_plane(mid.z))
                res.nonman_on_plane++;
            else {
                res.nonman_interior++;
                if (getenv("CONT_NMDBG"))
                    printf("        NM internal edge mid=(%.2f,%.2f,%.2f) len=%.2f\n",
                           mid.x, mid.y, mid.z,
                           sqrtf((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y)+(a.z-b.z)*(a.z-b.z)));
            }
        }
    }
    if (verbose && res.nonmanifold_edges > 0)
        printf("        nonman edges: %lld total, %lld on cell planes, %lld internal\n",
               res.nonmanifold_edges, res.nonman_on_plane, res.nonman_interior);

    // Connected components among vertices that are actually referenced.
    std::map<int,bool> seen;
    for (int c : canon) seen[dsu.find(c)] = true;
    res.components = (int)seen.size();

    if (getenv("CONT_COMPDBG") && res.components > 1) {
        // Per-component vertex count + bbox extent, to tell tiny internal voids
        // (small extent, few verts) from genuine fragmentation (large extent).
        std::map<int,int> cnt;
        std::map<int,Vector3> lo, hi;
        for (size_t i=0;i<canon.size();++i) {
            int root = dsu.find(canon[i]);
            const Vector3& v = soup.verts[i];
            if (!cnt.count(root)) { cnt[root]=0; lo[root]=v; hi[root]=v; }
            cnt[root]++;
            lo[root].x=fminf(lo[root].x,v.x); lo[root].y=fminf(lo[root].y,v.y); lo[root].z=fminf(lo[root].z,v.z);
            hi[root].x=fmaxf(hi[root].x,v.x); hi[root].y=fmaxf(hi[root].y,v.y); hi[root].z=fmaxf(hi[root].z,v.z);
        }
        for (auto& kv : cnt) {
            Vector3 e{ hi[kv.first].x-lo[kv.first].x, hi[kv.first].y-lo[kv.first].y, hi[kv.first].z-lo[kv.first].z };
            printf("        COMP root=%d verts=%d extent=(%.2f,%.2f,%.2f) ctr=(%.2f,%.2f,%.2f)\n",
                   kv.first, kv.second, e.x,e.y,e.z,
                   lo[kv.first].x+e.x*0.5f, lo[kv.first].y+e.y*0.5f, lo[kv.first].z+e.z*0.5f);
        }
    }

    // Normal continuity: a welded position shared by triangles from different
    // cells should carry one consistent shading normal. GenerateMesh smooths
    // normals only within a single cell, so boundary verts get mismatched
    // normals -> visible shading facets/seams even though geometry is welded.
    {
        std::unordered_map<int,Vector3> firstN;
        std::unordered_map<int,float>   minDot;
        for (size_t i=0;i<canon.size();++i) {
            Vector3 n = soup.norms[i];
            float len = sqrtf(n.x*n.x+n.y*n.y+n.z*n.z);
            if (len < 1e-6f) continue;
            n.x/=len; n.y/=len; n.z/=len;
            int c = canon[i];
            auto it = firstN.find(c);
            if (it == firstN.end()) { firstN[c]=n; minDot[c]=1.0f; }
            else {
                float d = n.x*it->second.x + n.y*it->second.y + n.z*it->second.z;
                if (d < minDot[c]) minDot[c] = d;
            }
        }
        const float cos15 = 0.96593f;
        for (auto& kv : minDot) {
            if (kv.second < cos15) {
                res.normal_seam_verts++;
                float ang = acosf(fmaxf(-1.0f,fminf(1.0f,kv.second))) * 180.0f/(float)M_PI;
                res.max_normal_angle = fmaxf(res.max_normal_angle, ang);
            }
        }
    }

    // Diagnostic: per-component vertex count + world bbox.
    if (getenv("CONT_VERBOSE")) {
        struct Agg { long long n=0; Vector3 lo{1e30f,1e30f,1e30f}, hi{-1e30f,-1e30f,-1e30f}; };
        std::map<int,Agg> agg;
        for (size_t i=0;i<canon.size();++i) {
            int r2 = dsu.find(canon[i]);
            Agg& a = agg[r2];
            a.n++;
            const Vector3& v = soup.verts[i];
            a.lo.x=fminf(a.lo.x,v.x); a.lo.y=fminf(a.lo.y,v.y); a.lo.z=fminf(a.lo.z,v.z);
            a.hi.x=fmaxf(a.hi.x,v.x); a.hi.y=fmaxf(a.hi.y,v.y); a.hi.z=fmaxf(a.hi.z,v.z);
        }
        int ci=0;
        for (auto& kv : agg) {
            const Agg& a = kv.second;
            printf("        comp[%d] verts=%lld bbox=[%.2f,%.2f,%.2f]..[%.2f,%.2f,%.2f]\n",
                   ci++, a.n, a.lo.x,a.lo.y,a.lo.z, a.hi.x,a.hi.y,a.hi.z);
        }
    }

    // DIAGNOSTIC: does surface.c actually emit the pure SDF gradient?
    // For each soup vertex, find the nearest particle center and compare the
    // actual mesh normal against the analytic normalize(v - nearestCenter).
    if (getenv("CONT_NDBG")) {
        int big = 0; float worst = 0.0f; int zeroN = 0;
        for (size_t i=0;i<soup.verts.size();++i) {
            const Vector3& v = soup.verts[i];
            float bd2=1e30f; Vector3 ctr{0,0,0};
            for (const auto& p : particles) {
                float dx=v.x-p.pos.x, dy=v.y-p.pos.y, dz=v.z-p.pos.z;
                float d2=dx*dx+dy*dy+dz*dz;
                if (d2<bd2){bd2=d2;ctr=p.pos;}
            }
            if (bd2<1e-12f) continue;
            float inv=1.0f/sqrtf(bd2);
            Vector3 exp{(v.x-ctr.x)*inv,(v.y-ctr.y)*inv,(v.z-ctr.z)*inv};
            Vector3 a=soup.norms[i];
            float al=sqrtf(a.x*a.x+a.y*a.y+a.z*a.z);
            if (al<1e-6f){zeroN++;continue;}
            a.x/=al;a.y/=al;a.z/=al;
            float dot=a.x*exp.x+a.y*exp.y+a.z*exp.z;
            float ang=acosf(fmaxf(-1.0f,fminf(1.0f,dot)))*180.0f/(float)M_PI;
            if (ang>15.0f) big++;
            worst=fmaxf(worst,ang);
        }
        printf("        NDBG: verts=%zu  off-gradient(>15deg)=%d  worst=%.1fdeg  zeroNorm=%d\n",
               soup.verts.size(), big, worst, zeroN);
    }

    // Coverage: sample the analytic union-of-spheres surface. A point on
    // particle i's sphere at radius (r - offset) is "exposed" if it is not
    // buried inside another particle. Adaptive isovalue shrinks the meshed
    // surface, so sample at the meshed radius and use a resolution-scaled
    // tolerance.
    //
    // 2A (decimation-aware): a full-res mesh resolves the surface at the grid
    // step, so 2 voxels of slack is the right bar. A decimated mesh legitimately
    // has larger triangles and cannot represent curvature finer than its own
    // edge length -- a flat triangle can sit up to ~one edge length from the
    // curved surface it spans. So the tolerance is the larger of the grid-scale
    // bar and the mesh's actual mean welded edge length (which equals ~gridStep
    // at full res and grows as ~1/sqrt(ratio) under QEM). This measures the mesh
    // we actually built rather than assuming a scaling law, and keeps full-res
    // strict (the grid-scale term dominates there).
    float gridStep = s / 15.0f;          // cellSize for divisionPow=4
    float meanEdge = edge_len_cnt ? (float)(edge_len_sum / (double)edge_len_cnt) : gridStep;
    float tol = fmaxf(gridStep * 2.0f, meanEdge * 1.5f);
    if (getenv("CONT_COVDBG"))
        printf("        COV tol=%.3f (gridStep=%.3f meanEdge=%.3f ratio=%.2f)\n",
               tol, gridStep, meanEdge, ratio);
    const int RINGS = 12, SECT = 24;
    for (const auto& pi : particles) {
        float meshR = meshed_radius(pi.r, s);
        if (meshR <= 0) continue;
        for (int a = 0; a <= RINGS; ++a) {
            float theta = (float)M_PI * a / RINGS;
            for (int b = 0; b < SECT; ++b) {
                float phi = 2.0f*(float)M_PI * b / SECT;
                Vector3 sp = {
                    pi.pos.x + meshR*sinf(theta)*cosf(phi),
                    pi.pos.y + meshR*sinf(theta)*sinf(phi),
                    pi.pos.z + meshR*cosf(theta)
                };
                // Exposed iff this point lies on the OUTER union boundary: it
                // must not be inside any other particle's meshed ball. The hard
                // union (min-distance field) puts the surface at the outer
                // envelope, so a sample strictly inside neighbor j's meshed
                // radius is interior to the solid and carries no surface.
                bool buried = false;
                float minSurfMargin = 1e30f;  // closest approach to any neighbor's surface
                for (const auto& pj : particles) {
                    if (&pj == &pi) continue;
                    float dx=sp.x-pj.pos.x, dy=sp.y-pj.pos.y, dz=sp.z-pj.pos.z;
                    float rj = meshed_radius(pj.r, s);
                    float dist = sqrtf(dx*dx+dy*dy+dz*dz);
                    if (dist*dist < rj*rj) { buried = true; break; }
                    minSurfMargin = fminf(minSurfMargin, dist - rj);
                }
                if (buried) continue;
                // 2A (decimation-aware): a sample exposed by less than one mesh
                // edge length sits in a crevice sliver thinner than the mesh can
                // resolve. A decimated mesh legitimately collapses such a feature
                // (a flat triangle bridges the crevice), so do not require
                // coverage there. Watertightness (boundary_edges==0) separately
                // guards against real holes, and full-res meshes have meanEdge
                // ~= gridStep so this only removes genuinely sub-resolution
                // points. Skipping a required point can never create a miss.
                if (minSurfMargin < meanEdge) continue;
                // Nearest-vertex pre-check (cheap): if any welded vertex is
                // within tol, the point is covered and we skip the triangle
                // scan. Dense full-res meshes hit this path almost always.
                float bestV = 1e30f;
                for (const Vector3& v : soup.verts) {
                    float dx=sp.x-v.x, dy=sp.y-v.y, dz=sp.z-v.z;
                    float d2 = dx*dx+dy*dy+dz*dz;
                    if (d2 < bestV) bestV = d2;
                }
                float d = sqrtf(bestV);
                if (d > tol) {
                    // Sparse/decimated mesh: a flat face can cover this sample
                    // even when no vertex is near. Fall back to exact
                    // point-to-triangle distance over the soup.
                    float bestT = bestV;
                    for (size_t t = 0; t + 2 < soup.verts.size(); t += 3) {
                        float d2 = point_tri_dist2(sp, soup.verts[t], soup.verts[t+1], soup.verts[t+2]);
                        if (d2 < bestT) bestT = d2;
                        if (bestT <= tol*tol) break;
                    }
                    d = sqrtf(bestT);
                }
                if (d > tol) {
                    res.coverage_misses++; res.max_gap = fmaxf(res.max_gap, d);
                    if (getenv("CONT_COVDBG")) {
                        // How deep inside the nearest OTHER particle is this miss?
                        // ratio < 1 => interior to the union (oracle false miss).
                        float bestRatio = 1e30f;
                        for (const auto& pj : particles) {
                            if (&pj == &pi) continue;
                            float dx=sp.x-pj.pos.x, dy=sp.y-pj.pos.y, dz=sp.z-pj.pos.z;
                            float r = sqrtf(dx*dx+dy*dy+dz*dz) / pj.r;
                            if (r < bestRatio) bestRatio = r;
                        }
                        printf("        COV miss @(%.2f,%.2f,%.2f) gap=%.2f nearestOtherRatio=%.2f\n",
                               sp.x,sp.y,sp.z, d, bestRatio);
                    }
                }
            }
        }
    }
    return res;
}

// Snap each interior (non-boundary) vertex back onto the analytic union surface
// to undo QEM's inward volume bias. Vertices on a cell face plane are skipped
// (the simplifier locks them, and moving them would tear the cross-cell seam).
// Projection is radial from the nearest particle center, so it does not change
// the SDF-gradient shading normal (same direction), only the position.
static void project_to_surface(Mesh& m, const std::vector<Particle>& sp, float pr,
                               Vector3 minB, Vector3 maxB, float s) {
    if (!m.vertices || m.vertexCount <= 0 || sp.empty()) return;
    float meshR = meshed_radius(pr, s);
    const float eps = 1e-4f;
    for (int i = 0; i < m.vertexCount; ++i) {
        float vx = m.vertices[i*3+0], vy = m.vertices[i*3+1], vz = m.vertices[i*3+2];
        if (fabsf(vx-minB.x)<eps || fabsf(vx-maxB.x)<eps ||
            fabsf(vy-minB.y)<eps || fabsf(vy-maxB.y)<eps ||
            fabsf(vz-minB.z)<eps || fabsf(vz-maxB.z)<eps) continue; // locked
        float bd2 = 1e30f; Vector3 c{0,0,0};
        for (const auto& p : sp) {
            float dx=vx-p.position.x, dy=vy-p.position.y, dz=vz-p.position.z;
            float d2 = dx*dx+dy*dy+dz*dz;
            if (d2 < bd2) { bd2 = d2; c = p.position; }
        }
        if (bd2 < 1e-12f) continue;
        float inv = meshR / sqrtf(bd2);
        m.vertices[i*3+0] = c.x + (vx-c.x)*inv;
        m.vertices[i*3+1] = c.y + (vy-c.y)*inv;
        m.vertices[i*3+2] = c.z + (vz-c.z)*inv;
    }
}

// ----------------------------------------------------------------------------
// Pipeline: build the combined mesh for a scene the way the cluster would.
// ----------------------------------------------------------------------------
static Soup build_scene(const std::vector<PIn>& particles, float s, float ratio) {
    Soup soup;

    // 1. CREATION: union of each particle's +/-2r coordinate box
    // (cluster.cpp:134, influence_radius = 2*r).
    std::unordered_map<CoordKey,bool,CoordHash> created;
    for (const auto& p : particles) {
        float inf = 2.0f * p.r;
        int x0=ifloor((p.pos.x-inf)/s), x1=ifloor((p.pos.x+inf)/s);
        int y0=ifloor((p.pos.y-inf)/s), y1=ifloor((p.pos.y+inf)/s);
        int z0=ifloor((p.pos.z-inf)/s), z1=ifloor((p.pos.z+inf)/s);
        for (int x=x0;x<=x1;++x) for (int y=y0;y<=y1;++y) for (int z=z0;z<=z1;++z)
            created[CoordKey{x,y,z}] = true;
    }

    // 2/3. For each created cell, assign intersecting particles, group by
    // material, and mesh each group over the cell box.
    for (auto& kv : created) {
        const CoordKey& C = kv.first;
        std::map<uint32_t, std::vector<int>> by_mat;
        for (int i = 0; i < (int)particles.size(); ++i) {
            if (box_intersects_sphere(C.x,C.y,C.z, s, particles[i].pos, particles[i].r))
                by_mat[particles[i].mat].push_back(i);
        }
        if (by_mat.empty()) continue;

        Bounds bounds;
        bounds.center = Vector3{ (C.x+0.5f)*s, (C.y+0.5f)*s, (C.z+0.5f)*s };
        bounds.size   = Vector3{ s, s, s };
        bounds.divisionPow = 4;

        Vector3 minB = Vector3{ (float)C.x*s, (float)C.y*s, (float)C.z*s };
        Vector3 maxB = Vector3{ (C.x+1)*s, (C.y+1)*s, (C.z+1)*s };

        for (auto& mg : by_mat) {
            std::vector<Particle> sp;
            sp.reserve(mg.second.size());
            float pr = particles[mg.second[0]].r;
            for (int idx : mg.second) {
                Particle q; q.position = particles[idx].pos; q.radius = particles[idx].r; q.materialId = (int)particles[idx].mat;
                sp.push_back(q);
            }
            Mesh m = GenerateMesh(sp.data(), pr, (int)sp.size(), bounds, 0.0f, NULL, 0);
            if (ratio < 1.0f && m.vertexCount > 0 && m.triangleCount > 0) {
                CellBounds cb; cb.min_bound = minB; cb.max_bound = maxB;
                SimplifyOptions so; so.target_ratio = ratio; so.lock_boundary = true;
                Mesh simp = simplify_mesh(m, so, &cb);
                if (simp.vertexCount > 0 && simp.triangleCount > 0) {
                    // QEM caves the surface inward; snap interior verts back
                    // onto the analytic surface to restore coverage, then reapply
                    // the SDF-gradient normals (radial snap keeps normal direction,
                    // but re-run is cheap and robust).
                    project_to_surface(simp, sp, pr, minB, maxB, s);
                    ComputeSurfaceNormals(&simp, sp.data(), pr, (int)sp.size(), 0.0f, NULL, 0);
                    append_mesh(soup, simp);
                    // free both CPU meshes (no GL involved)
                    if (simp.vertices) RL_FREE(simp.vertices);
                    if (simp.indices)  RL_FREE(simp.indices);
                    if (simp.normals)  RL_FREE(simp.normals);
                } else {
                    append_mesh(soup, m);
                }
            } else {
                append_mesh(soup, m);
            }
            if (m.vertices) RL_FREE(m.vertices);
            if (m.indices)  RL_FREE(m.indices);
            if (m.normals)  RL_FREE(m.normals);
        }
    }
    return soup;
}

// ----------------------------------------------------------------------------
// Matrix driver
// ----------------------------------------------------------------------------
struct Case {
    const char* id;
    const char* desc;
    std::vector<PIn> particles;
    float s;
    bool  expect_watertight;  // single closed surface expected?
    bool  expect_single_comp; // exactly one connected component expected?
    bool  expect_smooth = true; // no cross-cell normal seams expected?
};

static int g_unexpected = 0;

static void run_case(const Case& cs, float ratio, const char* ratioLabel) {
    Soup soup = build_scene(cs.particles, cs.s, ratio);
    OracleResult r = run_oracles(soup, cs.particles, cs.s, ratio);

    // Watertight = no outer cracks (boundary edges) and no cross-cell tearing
    // (non-manifold edges ON a cell plane). Interior non-manifold edges are the
    // hard-union marching-cubes sheet (1A): buried in the opaque solid, tracked
    // via r.nonman_interior but not a failure.
    bool wt_ok  = (!cs.expect_watertight) || (r.boundary_edges == 0 && r.nonman_on_plane == 0);
    bool cmp_ok = (!cs.expect_single_comp) || (r.components == 1);
    bool cov_ok = (r.coverage_misses == 0);
    bool seam_ok = (!cs.expect_smooth) || (r.normal_seam_verts == 0);
    bool pass = wt_ok && cmp_ok && cov_ok && seam_ok;

    printf("  [%-5s %-4s] tris=%-6lld bnd=%-5lld nonman=%-4lld(int=%-3lld) comp=%-3d covMiss=%-4d maxGap=%.3f nSeam=%-4d nAng=%.0f  %s\n",
           cs.id, ratioLabel, r.triangles, r.boundary_edges, r.nonmanifold_edges,
           r.nonman_interior, r.components, r.coverage_misses, r.max_gap,
           r.normal_seam_verts, r.max_normal_angle,
           pass ? "PASS" : "FAIL");

    if (!pass) {
        ++g_unexpected;
        if (!wt_ok)  printf("        -> NOT watertight (boundary=%lld, cell-plane nonmanifold=%lld): crack/flat-cap/tear\n", r.boundary_edges, r.nonman_on_plane);
        if (!cmp_ok) printf("        -> %d components: floating/unblended blob\n", r.components);
        if (!cov_ok) printf("        -> %d uncovered analytic surface samples (max gap %.3f): clipped/missing region\n", r.coverage_misses, r.max_gap);
        if (!seam_ok) printf("        -> %d normal-seam verts (max %.0f deg): cross-cell shading discontinuity\n", r.normal_seam_verts, r.max_normal_angle);
    }
}

// Two well-separated particles with different materialId, meshed as ONE field.
// surface.c bakes per-vertex material into mesh.colors via GetMaterialColor, so
// the produced mesh must carry more than one distinct material color.
static int test_per_vertex_material() {
    Particle ps[2];
    ps[0].position = (Vector3){-1.0f, 0, 0}; ps[0].radius = 0.8f; ps[0].materialId = 8;
    ps[1].position = (Vector3){ 1.0f, 0, 0}; ps[1].radius = 0.8f; ps[1].materialId = 9;
    Bounds b; b.center=(Vector3){0,0,0}; b.size=(Vector3){4,4,4}; b.divisionPow=4;
    Mesh m = GenerateMesh(ps, 0.8f, 2, b, 0.0f, NULL, 0);
    int distinctColors = 0;
    // Compares the R channel only; materialIds 8/9 map to Red/Green via
    // GetMaterialColor, so R alone (255 vs 0) is a sufficient distinctness signal.
    unsigned char c0r = (m.colors && m.vertexCount > 0) ? m.colors[0] : 0;
    for (int i = 0; i < m.vertexCount; ++i) {
        if (m.colors && m.colors[i*4] != c0r) { distinctColors = 1; break; }
    }
    if (!distinctColors) { printf("FAIL: expected >1 distinct vertex material color\n"); return 1; }
    return 0;
}

// Clip field: passing a foreign clip particle on the +x side must carve the
// group's isosurface so it terminates on the equidistant locus, pulling the
// mesh's max-x extent inward relative to the unclipped (open) mesh.
static int test_clip_carves_surface() {
    Particle g[1]; g[0].position=(Vector3){0,0,0}; g[0].radius=1.0f; g[0].materialId=8;
    Particle clip[1]; clip[0].position=(Vector3){1.2f,0,0}; clip[0].radius=1.0f; clip[0].materialId=4;
    Bounds b; b.center=(Vector3){0,0,0}; b.size=(Vector3){5,5,5}; b.divisionPow=4;
    Mesh open = GenerateMesh(g, 1.0f, 1, b, 0.0f, NULL, 0);          // no clip
    Mesh carved = GenerateMesh(g, 1.0f, 1, b, 0.0f, clip, 1);        // clipped on +x
    float maxOpen=-1e9f, maxCarved=-1e9f;
    for (int i=0;i<open.vertexCount;i++)   maxOpen   = fmaxf(maxOpen,   open.vertices[i*3]);
    for (int i=0;i<carved.vertexCount;i++) maxCarved = fmaxf(maxCarved, carved.vertices[i*3]);
    if (!(maxCarved < maxOpen - 0.05f)) { printf("FAIL: clip did not carve +x side (open=%.3f carved=%.3f)\n", maxOpen, maxCarved); return 1; }
    return 0;
}

// Clip-normal agreement with NON-ZERO blendWidth. The scalar clip in
// CalculateScalarAndMaterial carves the surface wherever -fO > <field value>,
// and in the smooth-min case that field value is the BLENDED value
// (fmin - k*ln(sum)) which is <= fmin. The per-vertex normal override in
// ComputeSurfaceNormals must fire on the SAME locus. The old code triggered on
// -fO > fmin (the hard min), so with blendWidth>0 there was a band where the
// scalar surface is carved but the normal override never fired -- those
// carved-wall vertices kept the (wrong) group gradient.
//
// Scene: two group particles offset in y so the smooth-min blend makes the
// field value strictly below the hard min near the +x carve, plus one clip
// particle off to +x (and +y) so the carve gradient -unit(v - c_clip) points in
// a clearly DIFFERENT direction than the group gradient unit(v - c_group). We
// mesh WITH a small non-zero blendWidth and the clip set (GenerateMesh runs
// ComputeSurfaceNormals internally with the same args), then check the carved
// (+x) vertices: their normals must match the foreign clip gradient, NOT the
// group gradient. Designed to FAIL under the old -fO > fmin trigger (carved-band
// verts keep the group normal) and PASS under the corrected -fO > fieldValue.
static int test_clip_normals_blended() {
    const float blendWidth = 0.20f;          // non-zero: exercises the blended path
    Particle g[2];
    g[0].position=(Vector3){0,-0.5f,0}; g[0].radius=1.0f; g[0].materialId=8;
    g[1].position=(Vector3){0, 0.5f,0}; g[1].radius=1.0f; g[1].materialId=8;
    Particle clip[1];
    clip[0].position=(Vector3){1.6f,0.9f,0}; clip[0].radius=1.0f; clip[0].materialId=4;
    Bounds b; b.center=(Vector3){0,0,0}; b.size=(Vector3){5,5,5}; b.divisionPow=4;

    Mesh carved = GenerateMesh(g, 1.0f, 2, b, blendWidth, clip, 1);
    if (carved.vertexCount == 0 || !carved.normals) {
        printf("FAIL: clip_normals_blended produced no mesh\n");
        return 1;
    }

    auto unit = [](Vector3 v)->Vector3{
        float l = sqrtf(v.x*v.x+v.y*v.y+v.z*v.z);
        if (l < 1e-9f) return Vector3{0,0,0};
        return Vector3{v.x/l, v.y/l, v.z/l};
    };

    // Reproduce surface.c's field math per vertex to find the discriminating
    // BAND: vertices where the clip carves the SMOOTH-MIN field value but NOT the
    // hard min, i.e. fmin >= -fO > fieldValue, with fieldValue = fmin - k*ln(sum),
    // sum = sum_j exp(-(f_j - fmin)/k). At those vertices the corrected trigger
    // (-fO > fieldValue) fires and shades them with the clip gradient
    // -unit(v - c_clip); the OLD trigger (-fO > fmin) does NOT fire and leaves the
    // group gradient unit(v - nearest group center). The two gradients are made to
    // point in clearly different directions (clip is off-axis), so the per-vertex
    // dot test cleanly separates fixed from broken.
    const float k = blendWidth;
    auto sdf = [](Vector3 v, Particle p)->float{
        float dx=v.x-p.position.x, dy=v.y-p.position.y, dz=v.z-p.position.z;
        return sqrtf(dx*dx+dy*dy+dz*dz) - p.radius;
    };

    int bandSamples = 0;   // vertices in the discriminating band
    int matchClip   = 0;   // ...whose normal follows the clip gradient (FIXED)
    int matchGroup  = 0;   // ...whose normal follows the group gradient (BROKEN)
    float worstClipDot = 1.0f;
    for (int i = 0; i < carved.vertexCount; ++i) {
        Vector3 v{ carved.vertices[i*3+0], carved.vertices[i*3+1], carved.vertices[i*3+2] };

        float f0 = sdf(v, g[0]), f1 = sdf(v, g[1]);
        float fmin = fminf(f0, f1);
        Vector3 cg = (f0 <= f1) ? g[0].position : g[1].position;
        float sum = expf(-(f0 - fmin)/k) + expf(-(f1 - fmin)/k);
        float fieldValue = fmin - k * logf(sum);   // <= fmin
        float fO = sdf(v, clip[0]);

        Vector3 gGroup = unit(Vector3{ v.x-cg.x, v.y-cg.y, v.z-cg.z });
        Vector3 gClip  = unit(Vector3{ clip[0].position.x-v.x, clip[0].position.y-v.y, clip[0].position.z-v.z });
        float sep = 1.0f - (gGroup.x*gClip.x + gGroup.y*gClip.y + gGroup.z*gClip.z);

        // Band: scalar surface carved (-fO > fieldValue) but the hard-min trigger
        // would NOT fire (-fO <= fmin), and the candidate gradients are separated
        // enough to make the dot test conclusive.
        bool inBand = (-fO > fieldValue) && (-fO <= fmin) && (sep > 0.25f);
        if (getenv("CLIPDBG"))
            printf("   v=(%.2f,%.2f,%.2f) fmin=%.3f field=%.3f -fO=%.3f sep=%.2f band=%d\n",
                   v.x,v.y,v.z, fmin, fieldValue, -fO, sep, inBand?1:0);
        if (!inBand) continue;

        Vector3 n = unit(Vector3{ carved.normals[i*3+0], carved.normals[i*3+1], carved.normals[i*3+2] });
        float dClip  = n.x*gClip.x  + n.y*gClip.y  + n.z*gClip.z;
        float dGroup = n.x*gGroup.x + n.y*gGroup.y + n.z*gGroup.z;
        bandSamples++;
        if (dClip > dGroup) { matchClip++;  worstClipDot = fminf(worstClipDot, dClip); }
        else                { matchGroup++; }
    }

    if (carved.vertices) RL_FREE(carved.vertices);
    if (carved.indices)  RL_FREE(carved.indices);
    if (carved.normals)  RL_FREE(carved.normals);
    if (carved.colors)   RL_FREE(carved.colors);

    if (bandSamples == 0) {
        printf("FAIL: clip_normals_blended found no band vertices to discriminate "
               "(scene tuning issue, not the code under test)\n");
        return 1;
    }
    // FIXED: every band vertex shades with the clip gradient (matchGroup == 0).
    // BROKEN (old -fO > fmin trigger): band vertices keep the group gradient, so
    // matchGroup > 0 and the test fails.
    if (matchGroup > 0) {
        printf("FAIL: %d/%d band vertices shaded with the group gradient instead of "
               "the clip gradient (worstClipDot=%.3f) -- normal clip triggers on the "
               "hard fmin, not the blended field value\n",
               matchGroup, bandSamples, worstClipDot);
        return 1;
    }
    return 0;
}

int main() {
    printf("=== Mesh continuity / edge-case matrix (headless, GL-free) ===\n");
    printf("Replicates cluster create(2r)/assign(r)/field(2.5r) + GenerateMesh + simplify.\n\n");

    // Per-vertex material color regression: surface.c must bake distinct
    // material colors for two well-separated particles with different materialId.
    printf("per_vertex_material: ");
    int mat_fail = test_per_vertex_material();
    g_unexpected += mat_fail;
    printf("%s\n", mat_fail == 0 ? "PASS" : "FAIL");
    printf("\n");

    // Clip field carve regression: a foreign clip particle must pull the
    // group's isosurface inward on the side facing it.
    printf("clip_carves_surface: ");
    int clip_fail = test_clip_carves_surface();
    g_unexpected += clip_fail;
    printf("%s\n", clip_fail == 0 ? "PASS" : "FAIL");
    printf("\n");

    // Clip-normal agreement with non-zero blendWidth: the normal override must
    // fire on the SAME blended field value the scalar clip carves, not the hard
    // min. Fails under the old -fO > fmin trigger when blendWidth>0.
    printf("clip_normals_blended: ");
    int clipn_fail = test_clip_normals_blended();
    g_unexpected += clipn_fail;
    printf("%s\n", clipn_fail == 0 ? "PASS" : "FAIL");
    printf("\n");

    const float s = 4.0f;  // smallest cell size (size_power 0)
    const uint32_t M0 = 0, M1 = 1;

    std::vector<Case> cases;

    // E1: single particle fully inside its owning cell. Baseline.
    cases.push_back({ "E1", "single particle centered in cell, r<s/2",
        { { {2,2,2}, 1.5f, M0 } }, s, true, true });

    // E2: single particle straddling ONE face (x=4 between cell 0 and 1).
    cases.push_back({ "E2", "single particle straddling one face",
        { { {4.0f,2,2}, 1.5f, M0 } }, s, true, true });

    // E3: straddling an edge (x=4 and y=4 -> 4 cells share).
    cases.push_back({ "E3", "single particle straddling an edge",
        { { {4.0f,4.0f,2}, 1.5f, M0 } }, s, true, true });

    // E4: straddling a corner (x=y=z=4 -> 8 cells share).
    cases.push_back({ "E4", "single particle straddling a corner",
        { { {4.0f,4.0f,4.0f}, 1.5f, M0 } }, s, true, true });

    // E5: particle larger than a cell (spans several cells).
    cases.push_back({ "E5", "particle radius > cell size",
        { { {2,2,2}, 5.0f, M0 } }, s, true, true });

    // E6: particle exactly on a cell face plane origin (pos = C*s).
    cases.push_back({ "E6", "particle centered exactly on cell corner",
        { { {0.0f,0.0f,0.0f}, 1.5f, M0 } }, s, true, true });

    // E7: two same-material particles overlapping across a cell boundary.
    cases.push_back({ "E7", "two same-material particles overlapping across boundary",
        { { {3.0f,2,2}, 1.5f, M0 }, { {5.0f,2,2}, 1.5f, M0 } }, s, true, true });

    // E8: two DIFFERENT-material particles overlapping (bands expected; separate
    // material meshes -> not asserted watertight, just observed).
    cases.push_back({ "E8", "two different-material particles overlapping",
        { { {3.0f,2,2}, 1.5f, M0 }, { {5.0f,2,2}, 1.5f, M1 } }, s, false, false, false });

    // E9: minimal assignment(r)-vs-field(2.5r) mismatch. Face at x=4 between
    // cell0 [0,4] and cell1 [4,8]. P1 sits in cell0 1.7 from the face (>r, so it
    // does NOT intersect cell1 -> NOT assigned there), P2 sits in cell1 and DOES
    // intersect cell0. The two spheres overlap (dist 2.7 < 3.0) so the blended
    // surface bulges across x=4 -- but cell1's field omits P1, so the two cells
    // contour the shared face from different particle sets.
    cases.push_back({ "E9", "overlap blended across a face where one particle is unassigned",
        { { {2.3f,2,2}, 1.5f, M0 }, { {5.0f,2,2}, 1.5f, M0 } }, s, true, true });

    // E10: dense small cloud spanning many cells (integration / regression).
    // The 3x3x3 lattice (spacing 1.6, r=1.2) leaves 8 genuine internal voids:
    // each 2x2x2 sub-cube's center is sqrt(3)*0.8 = 1.386 from its 8 corner
    // particles, i.e. 0.186 OUTSIDE every sphere, so the analytic union encloses
    // an air pocket there. The mesh correctly reproduces 1 outer surface + 8
    // void shells = 9 components, so single-component is NOT expected here.
    {
        std::vector<PIn> cloud;
        // deterministic 3x3x3 lattice with 1.6 spacing so spheres overlap and
        // cross many cell boundaries.
        for (int i=0;i<3;++i) for (int j=0;j<3;++j) for (int k=0;k<3;++k)
            cloud.push_back({ { 1.0f+i*1.6f, 1.0f+j*1.6f, 1.0f+k*1.6f }, 1.2f, M0 });
        cases.push_back({ "E10", "dense overlapping lattice (8 real internal voids)",
            cloud, s, true, false });
    }

    printf("Legend: bnd=boundary edges (cracks), nonman=non-manifold, comp=components,\n");
    printf("        covMiss=analytic surface samples with no nearby triangle.\n\n");

    for (const Case& cs : cases) {
        printf("%s: %s  (%zu particle%s)\n", cs.id, cs.desc, cs.particles.size(),
               cs.particles.size()==1?"":"s");
        run_case(cs, 1.0f,  "r1.0");
        run_case(cs, 0.23f, "r.23");
    }

    printf("\n%s (%d case-runs flagged)\n",
           g_unexpected == 0 ? "ALL EXPECTATIONS MET" : "FAILURES DETECTED",
           g_unexpected);
    return g_unexpected > 0 ? 1 : 0;
}
